#!/bin/bash

export DISPLAY=:0
status=$(amixer get Master | tail -n1 | awk '{print $NF}')
status=$(echo "${status%]}")
status=$(echo "${status#[}")
if [ $status == "on" ]
  then notify-send -i /usr/share/icons/powermate/volume-on.png " "
elif [ $status == "off" ]
  then notify-send -i /usr/share/icons/powermate/volume-mute.png " "
fi
amixer set Master toggle
